### ISSUE TITLE
NPE in CreateSequenceDictionary if the user does not indicate a reference.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/hellbender#273]
If you don't indicate the reference file with --REFERENCE a NPE is thrown.

Example:

$     java -jar ./build/libs/hellbender-all-1.0.jar CreateSequenceDictionary -OUTPUT=/tmp/1.dict

Exception in thread "main" java.lang.NullPointerException
	at org.broadinstitute.hellbender.tools.picard.sam.CreateSequenceDictionary.customCommandLineValidation(CreateSequenceDictionary.java:54)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:206)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:124)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:51)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:102)
	at org.broadinstitute.hellbender.Main.main(Main.java:117)

**Comment by droazen** [comment]
Verify that this is still happening, and if it is write a fix + new test case in `CreateSequenceDictionaryIntegrationTest`

**Comment by edwardkw** [comment]
Fixed.
