### ISSUE TITLE
CompareSAMs ignores validation stringency

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#419]
CompareSAMs ignores validation stringency

Running this

```
build/install/hellbender/bin/hellbender CompareSAMs src/test/resources/org/broadinstitute/hellbender/tools/BQSR/NA12878.chr17_69k_70k.dictFix.bam src/test/resources/org/broadinstitute/hellbender/tools/BQSR/NA12878.chr17_69k_70k.dictFix.bam --VALIDATION_STRINGENCY SILENT
```

results in this
```
htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 130, Read name 809R9ABXX101220:5:6:17918:145992, Mate Alignment start should be 0 because reference name = *.
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:439)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:643)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:628)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:598)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:544)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:518)
	at htsjdk.samtools.util.PeekIterator.peek(PeekIterator.java:67)
	at htsjdk.samtools.SecondaryOrSupplementarySkippingIterator.skipAnyNotprimary(SecondaryOrSupplementarySkippingIterator.java:36)
	at htsjdk.samtools.SecondaryOrSupplementarySkippingIterator.advance(SecondaryOrSupplementarySkippingIterator.java:31)
	at org.broadinstitute.hellbender.utils.read.SamComparison.compareCoordinateSortedAlignments(SamComparison.java:111)
	at org.broadinstitute.hellbender.utils.read.SamComparison.compareAlignments(SamComparison.java:68)
	at org.broadinstitute.hellbender.utils.read.SamComparison.<init>(SamComparison.java:44)
	at org.broadinstitute.hellbender.tools.picard.sam.CompareSAMs.doWork(CompareSAMs.java:34)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:94)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:144)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:51)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:77)
	at org.broadinstitute.hellbender.Main.main(Main.java:92)
```

Same command on original picard passes validation (though claims the bam is different from itself: https://github.com/broadinstitute/picard/issues/160)

Note to whoever fixes this: once this is fixed, re-enable code in BaseRecalibratorIntegrationTest.java
```
//IntegrationTestSpec.compareBamFiles(actualHiSeqBam_recalibrated, expectedHiSeqBam_recalibrated);
```

**Comment by cmnbroad** [comment]
Need some guidance here.  The CompareSAMs tool was not propagating the validation stringency. I have a fix for that, but that alone doesn't fix the compareBAMFiles test in BaseRecalibrationIntegrationTest.java, since that uses SamAssertionUtils.assertSamsEqual, which also doesn't propagate (or accept) a validation stringency. Changing SamAssertionUtils to use either SILENT or LENIENT does fix the integration test, and all the other tests pass, but it seems like a relaxing of the stringency, and I'm not sure it should be necessary to the BQSR test. If relaxing the stringency for BQSR test *IS* the right path, one possibility is to add a new method to SamAssertionUtils that accepts a validation stringency argument.

**Comment by cmnbroad** [comment]
Also, there are a bunch of other picard command line args that CompareSAMs is not propagating. It seems like these should be reviewed to see if they're candidates for this tool ?

**Comment by cmnbroad** [comment]
Note: there is a dataflow variant of BaseRecalibrator now, and the integration test for it has the same compareBamFiles test disabled. So I assume BaseRecalibratorDataFlowIntegrationTest.java also needs to be updated as part of this fix.

**Comment by akiezun** [comment]
@cmnbroad yes, please change the dataflow tests too.

**Comment by akiezun** [comment]
assigning to me to avoid confusion but @cmnbroad is working on it.

**Comment by akiezun** [comment]
@cmnbroad is this done now? if yes, please close
