### ISSUE TITLE
Write a helper to quickly go from function -> PTransform. 

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/hellbender#658]
We have a lot of code in Hellbender that's at its core a simple function, but it needs many lines of Dataflow boilerplate to wrap it into a transform.

It would be a great timesaver to create a helper function that goes from function to PTransform.

We might for example use it like this:

`PTransform<A,B> myTransform = Map.<A,B>of( a -> new B(a.start+1, a.end));`

references:
lambda syntax: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html
serializable lambdas: http://stackoverflow.com/questions/22807912/how-to-serialize-a-lambda

**Comment by lbergelson** [comment]
This++

**Comment by lbergelson** [comment]
I'll be happy to take a crack at this.

**Comment by jean-philippe-martin** [comment]
sure, go for it!

**Comment by lbergelson** [comment]
Blech, I can't figure out how to get it to work properly so you don't have to manually specify the output coder.


My implementation:
```
  public static <A,B> PCollection<B> apply(PCollection<? extends A> input, SerializableFunction<A, B> f){
        return input.apply(DataflowUtils.lift(f));
    }

    public static <A,B> PTransform<PCollection<? extends A>, PCollection<B>> lift(SerializableFunction<A, B> f){
        return ParDo.of(new DoFn<A, B>() {
            @Override
            public void processElement(ProcessContext c) throws Exception {
                c.output(f.apply(c.element()));
            }
        });
    }
```

example usage:
```
   @Test
    public void testApplyToString(){
        Pipeline p = GATKTestPipeline.create();
        PCollection<Integer> pints = p.apply(Create.of(Arrays.asList(1, 2, 3)));

        PCollection<String> presults = DataflowUtils.apply( pints, Object::toString).setCoder(StringUtf8Coder.of());

        DataflowAssert.that(presults).containsInAnyOrder("1","2","3");
        p.run();
    }
```

note the `setCoder` call, if you don't include that you get

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/louisb/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.7.7/25d160723ea37a6cb84e87cd70773ff02997e857/slf4j-jdk14-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/louisb/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.10/b3eeae7d1765f988a1f45ea81517191315c69c9e/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/louisb/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.5/6edffc576ce104ec769d954618764f39f0f0f10d/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
java.lang.IllegalStateException: Unable to infer a default Coder for AnonymousParDo.out [PCollection]; either correct the root cause below or use setCoder() to specify one explicitly. 
	at com.google.cloud.dataflow.sdk.values.TypedPValue.getCoder(TypedPValue.java:48)
	at com.google.cloud.dataflow.sdk.values.PCollection.getCoder(PCollection.java:137)
	at com.google.cloud.dataflow.sdk.transforms.windowing.Window$Bound.getDefaultOutputCoder(Window.java:286)
	at com.google.cloud.dataflow.sdk.transforms.windowing.Window$Bound.getDefaultOutputCoder(Window.java:221)
	at com.google.cloud.dataflow.sdk.transforms.PTransform.getDefaultOutputCoder(PTransform.java:334)
	at com.google.cloud.dataflow.sdk.values.TypedPValue.inferCoderOrFail(TypedPValue.java:152)
	at com.google.cloud.dataflow.sdk.values.TypedPValue.getCoder(TypedPValue.java:46)
	at com.google.cloud.dataflow.sdk.values.PCollection.getCoder(PCollection.java:137)
	at com.google.cloud.dataflow.sdk.transforms.View$AsIterable.apply(View.java:178)
	at com.google.cloud.dataflow.sdk.transforms.View$AsIterable.apply(View.java:165)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:74)
	at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner.apply(DirectPipelineRunner.java:217)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:291)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:225)
	at com.google.cloud.dataflow.sdk.values.PCollection.apply(PCollection.java:159)
	at com.google.cloud.dataflow.sdk.testing.DataflowAssert.that(DataflowAssert.java:93)
	at org.broadinstitute.hellbender.utils.dataflow.DataflowUtilsUnitTest.testApplyConvertToString(DataflowUtilsUnitTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.google.cloud.dataflow.sdk.coders.CannotProvideCoderException: Cannot provide a Coder for type variable B because the actual type is unknown due to erasure.
	at com.google.cloud.dataflow.sdk.coders.CoderRegistry.getDefaultCoder(CoderRegistry.java:545)
	at com.google.cloud.dataflow.sdk.coders.CoderRegistry.getDefaultCoder(CoderRegistry.java:516)
	at com.google.cloud.dataflow.sdk.coders.CoderRegistry.getDefaultCoder(CoderRegistry.java:165)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Bound.getDefaultOutputCoder(ParDo.java:741)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Bound.getDefaultOutputCoder(ParDo.java:660)
	at com.google.cloud.dataflow.sdk.transforms.PTransform.getDefaultOutputCoder(PTransform.java:334)
	at com.google.cloud.dataflow.sdk.values.TypedPValue.inferCoderOrFail(TypedPValue.java:152)
	at com.google.cloud.dataflow.sdk.values.TypedPValue.getCoder(TypedPValue.java:46)
	... 46 more

===============================================
Custom suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

**Comment by jean-philippe-martin** [comment]
It looks like generic's type erasure is getting in the way of Dataflow's auto-determination of the coder. Let me ask around.

**Comment by jean-philippe-martin** [comment]
It's not perfect, but one thing we can do is this:

````java
/**
 * SerializableFunction -> PTransform representing a map.
 */
public class Map {
    public static <A,B> PTransform<PCollection<? extends A>, PCollection<B>> of(SerializableFunction<A, B> f) {
        return ParDo.of(new DoFn<A, B>() {
            @Override
            public void processElement(ProcessContext c) throws Exception {
                c.output(f.apply(c.element()));
            }
        });
    }

    public static <A,B> PCollection<B> experiment(PCollection<? extends A> input, SerializableFunction<A,B> f, B sample) throws CannotProvideCoderException {
        Coder<B> coder = input.getPipeline().getCoderRegistry().getDefaultCoder(sample);
        return input.apply(Map.of(f)).setCoder(coder);
    }
}
````

You use it like this:

````java
    PCollection<Integer> p1 = pipeline.apply(Create.of(Arrays.asList(1, 2, 3)));
    PCollection<Integer> presults = Map.experiment(p1, x -> x + 1, 1);
````

**Comment by jean-philippe-martin** [comment]
Here's another way. It's not perfect either; it doesn't get rid of the DoFn. Type erasure really limits our options here.

````java
public class MapFn<A,B> extends DoFn<A,B> {
    protected SerializableFunction<A,B> fn;

    public MapFn(SerializableFunction<A,B> fn) {
        this.fn = fn;
    }

    @Override
    public void processElement(DoFn<A, B>.ProcessContext c) throws Exception {
       c.output(fn.apply(c.element()));
     }
}
````

Used like this:

````java
        PCollection<Integer> presults = pipeline
            .apply(Create.of(Arrays.asList(1, 2, 3)))
            .apply(ParDo.of(new MapFn<Integer, Integer>(x -> x + 1) {}));
````

**Comment by jean-philippe-martin** [comment]
To summarize our discussion: we prefer the style with `apply(Map.of(x -> x + 1, 1)`, except that instead of a sample we'll use the class. So: `apply(Map.of(x -> x + 1, Integer.class)`

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#31
