### ISSUE TITLE
Fix and reenable testGetInvalidPCollectionLocal()

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#774]
`ReadsDataflowSourceTest.testGetInvalidPCollectionLocal()` is failing with an exception.

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:569)
	at java.lang.StringBuilder.append(StringBuilder.java:190)
	at java.io.ObjectInputStream$BlockDataInputStream.readUTFSpan(ObjectInputStream.java:3147)
	at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3055)
	at java.io.ObjectInputStream$BlockDataInputStream.readLongUTF(ObjectInputStream.java:3038)
	at java.io.ObjectInputStream.readString(ObjectInputStream.java:1643)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1342)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.google.cloud.dataflow.sdk.coders.SerializableCoder.decode(SerializableCoder.java:124)
	at org.broadinstitute.hellbender.engine.dataflow.coders.GATKReadCoder.decode(GATKReadCoder.java:54)
	at org.broadinstitute.hellbender.engine.dataflow.coders.GATKReadCoder.decode(GATKReadCoder.java:27)
	at com.google.cloud.dataflow.sdk.coders.KvCoder.decode(KvCoder.java:100)
	at com.google.cloud.dataflow.sdk.coders.KvCoder.decode(KvCoder.java:42)
	at com.google.cloud.dataflow.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:135)
	at com.google.cloud.dataflow.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:118)
	at com.google.cloud.dataflow.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:112)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.ensureSerializableByCoder(SerializableUtils.java:145)
```
This was disabled as part of #754

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#17
