### ISSUE TITLE
PrintReads crashes on some inputs

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/hellbender#828]
I didn't expect Hellbender to crash for this command:

`$ ./hb PrintReads -I CEUTrio.HiSeq.WGS.b37.NA12878.bam -O 4m.bam -L 20:1000000-4000000`
(...)
[August 17, 2015 2:04:43 PM PDT] org.broadinstitute.hellbender.tools.PrintReads done. Elapsed time: 0.48 minutes.
Runtime.totalMemory()=412090368
java.lang.IllegalArgumentException: end must be >= start. start:2801961 end:2801960
	at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:33)
	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:45)
	at org.broadinstitute.hellbender.engine.ReadWalker.lambda$traverse$19(ReadWalker.java:64)
	at org.broadinstitute.hellbender.engine.ReadWalker$$Lambda$50/1094674892.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:63)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:370)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:97)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:150)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:71)
	at org.broadinstitute.hellbender.Main.main(Main.java:86)
jpmartin@hiseq:~/prog/GitHub/hellbender-main$

**Comment by lbergelson** [comment]
So the failing read is: `20FUKAAXX100202:7:2:11376:131531 2/2`

It's failing because it's cigar is `35S35I31S`.  The easiest thing to do would be to add NON_ZERO_REFERENCE_LENGTH_ALIGNMENT to the set of filters used by print reads in order to filter out this read.

**Comment by lbergelson** [comment]
Reproducible with the following small sam file [bad.sam](https://files.zenhub.io/55d255ffa33f044705b9db42)

```
hellbender PrintReads -I bad.sam -O out.bam
[August 17, 2015 5:44:44 PM EDT] org.broadinstitute.hellbender.tools.PrintReads  --output out.bam --input bad.sam  --disable_all_read_filters false --interval_set_rule UNION --interval_padding 0 --help false --version false --VERBOSITY INFO --QUIET false
[August 17, 2015 5:44:44 PM EDT] Executing as louisb@wm1b0-8ab on Mac OS X 10.9.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14; Version: Version:GATK.4.alpha-556-g73c02ea-SNAPSHOT JdkDeflater
17:44:44.990 [main] INFO  org.broadinstitute.hellbender.tools.PrintReads - Initializing engine
17:44:45.124 [main] INFO  org.broadinstitute.hellbender.tools.PrintReads - Done initializing engine
17:44:45.151 [main] INFO  org.broadinstitute.hellbender.engine.ReadsDataSource - Preparing readers for traversal
17:44:45.153 [main] INFO  org.broadinstitute.hellbender.engine.ReadsDataSource - Done preparing readers for traversal
17:44:45.178 [main] INFO  org.broadinstitute.hellbender.tools.PrintReads - Shutting down engine
[August 17, 2015 5:44:45 PM EDT] org.broadinstitute.hellbender.tools.PrintReads done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=257425408
java.lang.IllegalArgumentException: end must be >= start. start:2801961 end:2801960
	at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:33)
	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:45)
	at org.broadinstitute.hellbender.engine.ReadWalker.lambda$traverse$25(ReadWalker.java:64)
	at org.broadinstitute.hellbender.engine.ReadWalker$$Lambda$43/308889081.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:63)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:386)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:99)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:152)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:71)
	at org.broadinstitute.hellbender.Main.main(Main.java:86)
```

**Comment by lbergelson** [comment]
Or actually, with the more minimal:

```
@HD	VN:1.0	GO:none	SO:coordinate
@SQ	SN:20	LN:63025520
@RG	ID:20FUK.7	PL:illumina	PU:20FUKAAXX100202.7	LB:Solexa-18483	SM:NA12878	CN:BI
@PG	ID:GATK IndelRealigner	VN:1.2-573-g821421d	CL:knownAlleles=[(RodBinding name=knownAlleles source=/humgen/gsa-hpprojects/GATK/data/Comparisons/Validated/dbSNP/dbsnp_132_b37.leftAligned.vcf), (RodBinding name=knownAlleles2 source=/humgen/1kg/processing/official_release/phase1/projectConsensus/ALL.wgs.projectConsensus_v2b.20101123.snps.sites.vcf), (RodBinding name=knownAlleles3 source=/humgen/gsa-hpprojects/GATK/data/Comparisons/Unvalidated/AFR+EUR+ASN+1KG.dindel_august_release_merged_pilot1.20110126.sites.vcf)] LODThresholdForCleaning=5.0 consensusDeterminationModel=USE_READS entropyThreshold=0.15 maxReadsInMemory=150000 maxIsizeForMovement=3000 maxPositionalMoveAllowed=200 maxConsensuses=30 maxReadsForConsensuses=120 maxReadsForRealignment=20000 noOriginalAlignmentTags=false nWayOut=null generate_nWayOut_md5s=false check_early=false noPGTag=false keepPGTags=false indelsFileForDebugging=null statisticsFileForDebugging=null SNPsFileForDebugging=null
@PG	ID:GATK TableRecalibration	VN:1.2-573-g821421d	CL:default_read_group=null default_platform=null force_read_group=null force_platform=null window_size_nqs=5 homopolymer_nback=7 exception_if_no_tile=false solid_recal_mode=SET_Q_ZERO solid_nocall_strategy=THROW_EXCEPTION recal_file=/humgen/gsa-firehose2/carneiro/b37_decoy/CEUTrio.HiSeq.WGS.b37.NA12878.pre_recal.csv preserve_qscores_less_than=5 smoothing=1 max_quality_score=50 doNotWriteOriginalQuals=false no_pg_tag=false fail_with_no_eof_marker=false skipUQUpdate=false Covariates=[ReadGroupCovariate, QualityScoreCovariate, CycleCovariate, DinucCovariate]
@PG	ID:bwa	PN:bwa	VN:0.5.9-r16
20FUKAAXX100202:7:2:11376:131531	147	20	2801961	39	35S35I31S	=	2801635	-325	GGTCTGGGGCTGGGAGAGAAATCCCAAGCCCGGCCCGGTTGGGAGGCCGTGGGCATCCACACGGGGAATGGCCCGGCCCGGTTGGGAGGCCGTGGGCATCC	####################################=3;7<9>?;A:*1CBF<GG>GGFGF?FFBFFGGFFGG>FFGG>FEGFDFFGFFF=CFECBAC=DA	OC:Z:35S35M31S	XC:i:66	RG:Z:20FUK.7	XG:i:0	AM:i:29	NM:i:35	SM:i:29	XM:i:1	XO:i:0	OP:i:2801969	BQ:Z:@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
